# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconfiguration',
            name='consumer_id',
            field=models.CharField(blank=True, help_text='Consumer identifier of a registered app', max_length=255, null=True, verbose_name='Consumer Id'),
        ),
    ]
