# Generated by Django 2.0.7 on 2018-10-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0004_testconfiguration_counterparty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(help_text='Test Profile id', verbose_name='Profile id')),
                ('operation_id', models.CharField(blank=True, help_text='Test endpoint opreation id', max_length=255, null=True, verbose_name='Operation id ')),
                ('json_body', models.TextField(help_text='The json body to the  test request', max_length=65535, verbose_name='Json body')),
            ],
            options={
                'verbose_name': 'Test Profile Operation',
                'verbose_name_plural': 'Test Profile Operation',
            },
        ),
        migrations.AlterField(
            model_name='testconfiguration',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this configuration', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
