# Generated by Django 2.0.7 on 2018-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0007_auto_20181115_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileoperation',
            name='is_deleted',
            field=models.IntegerField(default=0, help_text='Deleted', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='profileoperation',
            name='remark',
            field=models.CharField(blank=True, help_text='remark', max_length=255, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='profileoperation',
            name='replica_id',
            field=models.IntegerField(default=1, help_text='Test Replica id', verbose_name='Replica id'),
        ),
        migrations.AlterField(
            model_name='profileoperation',
            name='order',
            field=models.IntegerField(default=100, help_text='Test order', verbose_name='Order'),
        ),
    ]
