# Generated by Django 2.0.7 on 2020-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0008_auto_20181227_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileoperation',
            name='method',
            field=models.CharField(blank=True, help_text='method', max_length=255, verbose_name='method'),
        ),
        migrations.AddField(
            model_name='profileoperation',
            name='save_time',
            field=models.CharField(blank=True, help_text='save_time', max_length=255, verbose_name='save_time'),
        ),
        migrations.AlterField(
            model_name='testconfiguration',
            name='name',
            field=models.CharField(help_text='Name of the configuration', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
