# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the configuration', max_length=255, verbose_name='Name')),
                ('username', models.CharField(blank=True, help_text='Username', max_length=255, null=True, verbose_name='Username')),
                ('bank_id', models.CharField(blank=True, help_text='Bank identifier', max_length=255, null=True, verbose_name='Bank Id')),
                ('branch_id', models.CharField(blank=True, help_text='Bank branch identifier', max_length=255, null=True, verbose_name='Branch Id')),
                ('atm_id', models.CharField(blank=True, help_text='ATM identifier', max_length=255, null=True, verbose_name='ATM Id')),
                ('account_id', models.CharField(blank=True, help_text='Account identifier', max_length=255, null=True, verbose_name='Account Id')),
                ('other_account_id', models.CharField(blank=True, help_text='Account identifier of another account', max_length=255, null=True, verbose_name='Other Account Id')),
                ('view_id', models.CharField(blank=True, help_text='View identifier', max_length=255, null=True, verbose_name='View Id')),
                ('user_id', models.CharField(blank=True, help_text='User identifier', max_length=255, null=True, verbose_name='User Id')),
                ('provider_id', models.CharField(blank=True, help_text='Provider identifier', max_length=255, null=True, verbose_name='Provider Id')),
                ('customer_id', models.CharField(blank=True, help_text='Customer identifier', max_length=255, null=True, verbose_name='Customer Id')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction identifier', max_length=255, null=True, verbose_name='Transaction Id')),
                ('from_currency_code', models.CharField(blank=True, help_text='Currency code to convert from', max_length=255, null=True, verbose_name='From Currency Code')),
                ('to_currency_code', models.CharField(blank=True, help_text='Currency code to convert to', max_length=255, null=True, verbose_name='To Currency Code')),
                ('product_code', models.CharField(blank=True, help_text="Product code of a bank's product", max_length=255, null=True, verbose_name='Product Code')),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting identifier of a bank\\s meeting', max_length=255, null=True, verbose_name='Meeting Id')),
                ('owner', models.ForeignKey(help_text='User who owns this configuration', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'Test Configurations',
                'verbose_name': 'Test Configuration',
            },
        ),
    ]
