# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0005_auto_20181029_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileoperation',
            name='order',
            field=models.IntegerField(default=0, help_text='Test order', verbose_name='Order'),
        )
    ]
