# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0006_auto_20181108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileoperation',
            name='urlpath',
            field=models.CharField(blank=True, help_text='The url', max_length=255, null=True, verbose_name='The url'),
        ),
    ]
